### PR TITLE
Add "Current" and "Latest" labels of the model

### PR DESCRIPTION
**Pull request by orelgueta**
This PR should answer #66. I essentially added a metadata collection to our DB to keep the information of what is the "Current" and what is the "Latest" Telescope Model tag. Currently the two are the same (Prod5), but in the future I expect the "latest" to include the latest changes, while the "Current" should be actual productions. Once construction is over, this will be replaced by a more sophisticated system of course.
I suggest that the default from now on is "Current". This is what I set it in "TelescopeModel".

### CODE REVIEW

**Review by RaulRPrado — COMMENTED** [review]
Looks all fine.

I will change the default model in the application and in some other tests (if needed) and then you can merge it.

**Comment by RaulRPrado** [comment]
Actually I'll not do that.

In the tests, it should stay prod4 and the applications are being changed in my docs branch.

**Comment by RaulRPrado** [comment]
You may merge it!

**Comment by orelgueta** [comment]
> In the tests, it should stay prod4 and the applications are being changed in my docs branch.

Why should it stay prod4? Why not the stable tag? I assume the tests will evolve with the tags as well and should be up-to-date with the model no? 
And what about prod5 instead of prod4?

**Comment by RaulRPrado** [comment]
> > In the tests, it should stay prod4 and the applications are being changed in my docs branch.
> 
> Why should it stay prod4? Why not the stable tag? I assume the tests will evolve with the tags as well and should be up-to-date with the model no?
> And what about prod5 instead of prod4?

These tests should not test the model, but only the code. We should pick a model version which we know that will work so we can effectively test the code.
We might want to test the model itself somehow, but this should be done separately.

I assume it's going to happen often that the Latest model will be broken. In this situation, we should still be able to test any change on the code independently.

That is my position. What do you think?

**Comment by orelgueta** [comment]
I agree completely, that's why I created two "defaults", "Current" and "Latest". The latest may be broken every now and then, but the "Current" should be stable, working and point only to production tags like prod4, prod5, etc. I think our tests should work for any stable model and not stay behind, checking only a specific old model like prod4.

**Comment by RaulRPrado** [comment]
> I agree completely, that's why I created two "defaults", "Current" and "Latest". The latest may be broken every now and then, but the "Current" should be stable, working and point only to production tags like prod4, prod5, etc. I think our tests should work for any stable model and not stay behind, checking only a specific old model like prod4.

Ok ok. This means that the Current version will always be tested and stable. In this case make sense to use the Current one for the testing. I'll do that

**Comment by RaulRPrado** [comment]
I did the changes on the tests.
The application I'll keep as they are by now because I'll change it on the other branch. If I change then here, I'll be creating conflicts  already.

**Comment by orelgueta** [comment]
Thanks! I changed the "current" to "Current" cause that's how it appears in the DB. Maybe in the future I will implement case insensitive search, but for now it's easier this way.
I will merge now then.

**Comment by RaulRPrado** [comment]
> Thanks! I changed the "current" to "Current" cause that's how it appears in the DB. Maybe in the future I will implement case insensitive search, but for now it's easier this way.
> I will merge now then.

I used "current" because the validateModelVersion do the job of converting it to "Current". It's a similar system as for the telescope names.

**Comment by orelgueta** [comment]
Don't we have to add "current" to the "Current" list then?

https://github.com/gammasim/gammasim-tools/blob/d5bea7faac60d0bae3db3ef815439525db1aeeea/simtools/util/names.py#L332

**Comment by RaulRPrado** [comment]
No, different capitalizations are automatically accepted. That is why we can write all the alternative names in low case.

**Comment by orelgueta** [comment]
Ahh, OK now I see, very nice!
Should I change it back or is it OK to leave it like this?

**Comment by RaulRPrado** [comment]
No, don't worry. It's not that important.

**Comment by orelgueta** [comment]
OK, thanks for the review!

**Pull request merged**
