### PR TITLE
Use Regex to identify we are in the testeff table

### PR DESCRIPTION
**Pull request by orelgueta**
Done, but tested only with the dat file you gave me for LST (since I can't install sim_telarray yet). I assume it should be fine for all files though, it's very simple.

### CODE REVIEW

**Comment by RaulRPrado** [comment]
I cannot checkout testeff_table and it doesn't show up when I do git branch -a
Any idea?

**Comment by orelgueta** [comment]
No idea, when I follow the steps [here](https://stackoverflow.com/questions/12762922/git-cannot-see-new-remote-branch) it looks OK.

**Comment by RaulRPrado** [comment]
In my tests flashcam, nectarcam, lst and sst-1m worked.

sst-gct and astri didn't but I don't know if we should worry about it. 

We need to set the name for the new SST (Camera + Structure), which will probably be "SST", right? This should be done in another PR, not here.

**Comment by orelgueta** [comment]
Yes, I would say SST would be good.
I do worry though about gct and astri, considering those are the ones composing the SST...
Why didn't it work? Because of the new reader? That would be surprising.

**Comment by orelgueta** [comment]
Also, can you please copy paste the results you get for the various telescopes (the new printout I added)? I would like to compare to Konrad's results.
(I will try work on installing sim_telarray locally, but it's a little beyond me the compiler issues it produces.)

**Comment by RaulRPrado** [comment]
1) The branch: it was just a matter of updating my local repository. Basic git stuff that I'm still learning

**Comment by RaulRPrado** [comment]
2) The error with astri is this: 
Traceback (most recent call last):
  File "applications/validate_camera_efficiency.py", line 68, in <module>
    ce.analyze(force=True)
  File "/home/prado/Work/Projects/CTA_MC/gammasim-tools/simtools/camera_efficiency.py", line 296, in analyze
    self._logger.info('Spectrum weighted reflectivity: {}'.format(self.calcReflectivity()))
  File "/home/prado/Work/Projects/CTA_MC/gammasim-tools/simtools/camera_efficiency.py", line 404, in calcReflectivity
    c1ReducedWL = self._results['C1'][
  File "/home/prado/anaconda3/envs/gammasim-tools-dev/lib/python3.7/site-packages/astropy/table/table.py", line 1602, in __getitem__
    return self.columns[item]
  File "/home/prado/anaconda3/envs/gammasim-tools-dev/lib/python3.7/site-packages/astropy/table/table.py", line 239, in __getitem__
    return OrderedDict.__getitem__(self, item)
KeyError: 'C1'

I'm debugging it now.

**Comment by RaulRPrado** [comment]
I think it doesn't find the table. self._results is empty

**Comment by RaulRPrado** [comment]
No no, the simtel output is empty. It might be a model issue then.

**Comment by orelgueta** [comment]
OK, will wait to see what the issue is and see the comparison between our results and Konrad's.

**Comment by RaulRPrado** [comment]
See attached log files for astri and flashcam. 
[camera-efficiency-MST-FlashCam-za20.0_validate-camera-efficiency.log](https://github.com/gammasim/gammasim-tools/files/4850627/camera-efficiency-MST-FlashCam-za20.0_validate-camera-efficiency.log)
[camera-efficiency-SST-2M-ASTRI-za20.0_validate-camera-efficiency.log](https://github.com/gammasim/gammasim-tools/files/4850629/camera-efficiency-SST-2M-ASTRI-za20.0_validate-camera-efficiency.log)

**Comment by RaulRPrado** [comment]
Astri model points to funnel_perfect.dat file, is that right?

Error: Table with 4 rows has been read from file funnel_perfect.dat

**Comment by RaulRPrado** [comment]
Ok, that is correct. sim_telarray is probably not finding the file, which is in cfg/common, not in cfg/CTA

**Comment by RaulRPrado** [comment]
It's all fine with that. Sorry about the live debugging. I'll stop now and come back after I fix it.

**Comment by orelgueta** [comment]
Yes, that is all correct, funnel_perfect is used for cameras without funnels and indeed it is not in cfg/CTA. I had to copy it to the dat files directory as well to avoid such issues. Don't worry about live debugging, if I read your messages live, I could have saved you a step or two.

**Comment by RaulRPrado** [comment]
Ok, I found the bug now.
For mirror_class = 2, the mirror_list is 'none' in the model and testeff was breaking trying to find a file called 'none'.
Now, if mirror_class=2, I will skip the fmir option of testeff. Everything seems to be working now.
I'll send the results next.

**Comment by RaulRPrado** [comment]
ASTRI
Spectrum weighted reflectivity: 0.9158008881525233
Camera nominal efficiency with gaps (B-TEL-1170): 0.44009439940018713
Telescope total efficiency with gaps (was A-PERF-2020): 0.5207902797289903
Total telescope Cherenkov light eff./sqrt(NSB total eff.) (A-PERF-2025/B-TEL-0090): 0.44525389993400766

GCT
Spectrum weighted reflectivity: 0.7350884458200477
Camera nominal efficiency with gaps (B-TEL-1170): 0.4329047908875005
Telescope total efficiency with gaps (was A-PERF-2020): 0.4202935538843951
Total telescope Cherenkov light eff./sqrt(NSB total eff.) (A-PERF-2025/B-TEL-0090): 0.3972117799569855

SST-1M
Spectrum weighted reflectivity: 0.8875238265648399
Camera nominal efficiency with gaps (B-TEL-1170): 0.3409135439548363
Telescope total efficiency with gaps (was A-PERF-2020): 0.3046226544250746
Total telescope Cherenkov light eff./sqrt(NSB total eff.) (A-PERF-2025/B-TEL-0090): 0.5336877233590326

**Comment by RaulRPrado** [comment]
MST-FlashCam
Spectrum weighted reflectivity: 0.9438313601918018
Camera nominal efficiency with gaps (B-TEL-1170): 0.25462112488771294
Telescope total efficiency with gaps (was A-PERF-2020): 0.25823221883585074
Total telescope Cherenkov light eff./sqrt(NSB total eff.) (A-PERF-2025/B-TEL-0090): 0.4853092750049995

MST-NectarCam
Spectrum weighted reflectivity: 0.9438313601918018
Camera nominal efficiency with gaps (B-TEL-1170): 0.25050809231458204
Telescope total efficiency with gaps (was A-PERF-2020): 0.25387964483561665
Total telescope Cherenkov light eff./sqrt(NSB total eff.) (A-PERF-2025/B-TEL-0090): 0.4795888960251189

**Comment by RaulRPrado** [comment]
@orelgueta , you can merge the PR if you think everything is fine now.

**Comment by orelgueta** [comment]
Thanks for fixing the issue and the results.
FlashCam and NectarCam agree with Konrad's values up to a few per-mill. I guess this is good enough.
SST-1M and GCT agree with the Prod4 values as well, not surprising.
ASTRI is quite off though, in particular, the reflectivity is much higher than it was in prod4 (91% to 77%). Can you check if something went wrong there? Is there a chance the mirror reflectivity wasn't taken into account at all?

**Comment by RaulRPrado** [comment]
Yes, something did go wrong:

Error in line 12 of file transmission_astri_window_new.dat (expcting 2 values, found 0).
Warning: Quantum efficiency not dropping to zero for long wavelengths.
Interpolation error.
Interpolation error.
Interpolation error.
Interpolation error.
(...)

**Comment by RaulRPrado** [comment]
The file is in a very different format than  transmission_astri_window_average.dat.
Any idea?

**Comment by orelgueta** [comment]
OK that's actually important since this is also used for the CHEC on ASTRI setup. This file uses a 2D transmission which should be turned on automatically when sim_telarray detects #@RPOL@ in the beginning of the file.

**Comment by orelgueta** [comment]
How does your command to run testeff compare with 

bin/testeff -nm -alt 2150 -fatm atm_trans_2150_1_10_0_0_2150.dat -flen 2.15 -fcur 4.3 -spix 0.620 -fmir fake_astri_mirrorpos.dat -fref ref_astri_2017-06_T0.dat -m2 -teltrans 0.92362 -camtrans 1 -fflt transmission_astri_window_average.dat -fang funnel_perfect.dat -fwl none -fqe PDE_V_4.4V_LVR5_ext.txt 300 550 300 26 20?

**Comment by RaulRPrado** [comment]
bin/testeff -nm -nsb-extra -alt 2150. -fatm atm_trans_2150_1_10_0_0_2150.dat -flen 2.15191 -fcur 4.3 -spix 0.6975 -fref ref_astri-2d_2018-01-17.dat -m2 -teltrans 0.92362 -camtrans 1 -fflt transmission_astri_window_new.dat -fang funnel_perfect.dat -fwl none -fqe PDE_V_4.4V_LVR5_ext.txt 200 1000 300 1 20 2>/home/prado/Work/Projects/CTA_MC/gammasim-tools/simtools-files/validate-camera-efficiency/camera-efficiency/camera-efficiency-SST-2M-ASTRI-za20.0_validate-camera-efficiency.log >/home/prado/Work/Projects/CTA_MC/gammasim-tools/simtools-files/validate-camera-efficiency/camera-efficiency/camera-efficiency-SST-2M-ASTRI-za20.0_validate-camera-efficiency.dat

**Comment by orelgueta** [comment]
hmm, my best guess is that testeff doesn't know to use the 2D interpolation like sim_telarray. So Konrad used the average transmission rather than the 2D one. I will write to ask him.

**Comment by RaulRPrado** [comment]
Ok

**Comment by RaulRPrado** [comment]
Should we merge this PR then?

**Comment by orelgueta** [comment]
I would wait to hear from Konrad. If testeff cannot handle 2D interpolation, we need to add a case for that in the code for now, and use a 1D transmission, no?

**Comment by RaulRPrado** [comment]
Ok, no problem.

**Comment by RaulRPrado** [comment]
I don't remember exactly what we concluded about this PR. I'll implement the astri case. It will be ugly but hopefully we can do it better in the future.

**Comment by orelgueta** [comment]
We concluded that you implement the ASTRI case, post the values with the correction and if they agree with Konrad's values, we can merge this PR and close #36 .

**Comment by RaulRPrado** [comment]
@orelgueta, see below results for ASTRI using the average camera filter file.

Spectrum weighted reflectivity: 0.9158008881525233
Camera nominal efficiency with gaps (B-TEL-1170): 0.4012759008175439
Telescope total efficiency with gaps (was A-PERF-2020): 0.41392735330742664
Total telescope Cherenkov light eff./sqrt(NSB total eff.) (A-PERF-2025/B-TEL-0090): 0.5044666732521034

**Comment by orelgueta** [comment]
The spectrum weighted reflectivity didn't change:

Old: Spectrum weighted reflectivity: 0.9158008881525233
New: Spectrum weighted reflectivity: 0.9158008881525233

**Comment by orelgueta** [comment]
Also, did you run ASTRI? Or ASTRI plus CHEC (i.e., SST)?

**Comment by RaulRPrado** [comment]
I ran ASTRI

**Comment by RaulRPrado** [comment]
> The spectrum weighted reflectivity didn't change:
> 
> Old: Spectrum weighted reflectivity: 0.9158008881525233
> New: Spectrum weighted reflectivity: 0.9158008881525233

Was it suppose to? Are Konrad's number for prod5 as well?

**Comment by orelgueta** [comment]
OK, so we need ASTRI+CHEC (the ASTRI part is where the issue is, but we have the latest ASTRI+CHEC numbers).

And yes, it should change. The spectrum weighted reflectivity should be around 0.77 (see - https://www.mpi-hd.mpg.de/hfm/CTA/MC/Prod4/Config/Efficiencies/p4eff_ASTRI+CHEC-S.pdf)

The values for prod4 and prod5 should be almost identical, there were no changes since prod4.

**Comment by RaulRPrado** [comment]
Ok. ASTRI+CHEC = SST-Structure + SST-Camera, right?
I'll prepare the names to run the new SST soon.

**Comment by orelgueta** [comment]
Yes, that is correct. If you prefer to a do a quick test first just to check your fix, running ASTRI is OK. I would expect the spectrum weighted reflectivity to be around 0.77 regardless of the camera or which production we are using (unless there's a very big change I am missing).

**Comment by RaulRPrado** [comment]
SST out of the box is still not fine.

Spectrum weighted reflectivity: 0.9158008881525233
Camera nominal efficiency with gaps (B-TEL-1170): 0.3947204512676613
Telescope total efficiency with gaps (was A-PERF-2020): 0.40716522312120085
Total telescope Cherenkov light eff./sqrt(NSB total eff.) (A-PERF-2025/B-TEL-0090): 0.5003290917049251

**Comment by RaulRPrado** [comment]
From simtel log:

Warning: Quantum efficiency not dropping to zero for long wavelengths.
Interpolation error.
Interpolation error.
Interpolation error.
(...)

I'll keep debugging it tomorrow.

**Comment by orelgueta** [comment]
Interesting, I assume it is still a 2D optical issue since the spectrum weighted average is still almost 15% too high. Did you exchange the ref_astri-2d_2018-01-17.dat you used before to the one-dimensional ref_astri_2017-06_T0.dat?

**Comment by RaulRPrado** [comment]
> Interesting, I assume it is still a 2D optical issue since the spectrum weighted average is still almost 15% too high. Did you exchange the ref_astri-2d_2018-01-17.dat you used before to the one-dimensional ref_astri_2017-06_T0.dat?

Now I did. It seems to be working now, see below.

Spectrum weighted reflectivity: 0.7747220257059302
Camera nominal efficiency with gaps (B-TEL-1170): 0.3947204512676613
Telescope total efficiency with gaps (was A-PERF-2020): 0.3472310477169944
Total telescope Cherenkov light eff./sqrt(NSB total eff.) (A-PERF-2025/B-TEL-0090): 0.4501101459606101

**Comment by orelgueta** [comment]
Yes, now the differences are at the per-mill level. We can merge this PR then. I will let you do that and I will close #36.

**Comment by RaulRPrado** [comment]
Great =)

It wasn't a beautiful solution, but we can do it better in the future.

**Pull request merged**
