### PR TITLE
Core mission

### PR DESCRIPTION
**Pull request by GernotMaier**
Update of the description of the main aims of gammasim-tools

### CODE REVIEW

**Comment by RaulRPrado** [comment]
Fine for me. @orelgueta ?

**Comment by orelgueta** [comment]
Looks fine to me, but do we want to comply with the name we used in the concept document, i.e., Simulation Pipelines System? To be honest, I really don't like the "Pipelines" there, but it was forced on us, and we might have to live with it everywhere.

**Comment by GernotMaier** [comment]
I would leave it out - you’ve seen how confusing this name was for Francesco (a system of pipelines?)

> On 25. May 2020, at 14:40, orelgueta <notifications@github.com> wrote:
> 
> 
> Looks fine to me, but do we want to comply with the name we used in the concept document, i.e., Simulation Pipelines System? To be honest, I really don't like the "Pipelines" there, but it was forced on us, and we might have to live with it everywhere.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 



---
Dr Gernot Maier
CTA
Deutsches Elektronen-Synchrotron DESY 
Ein Forschungszentrum der Helmholtz-Gemeinschaft
Platanenallee 6, D-15738 Zeuthen, Germany

Tel.: +49  33 7627 7598
Internet: www.desy.de/cta
Besucheradresse: 1X07

**Comment by orelgueta** [comment]
OK, so we can merge (will do so myself now).

**Pull request merged**
