### PR TITLE
Add option to get site parameter, remove getting multiple versions

### LINKED ISSUE #384: applications/get_parameter.py does not work for getting parameter from a site
When writing the documentation for applications/get_parameter.py, I realized it does not work for getting parameter from a site, for instance, the altitude. It would be nice to have it implemented. Adding such a test to the integration tests would also be necessary.

### PR DESCRIPTION
**Pull request by orelgueta**
Fixes #384

### CODE REVIEW

**Review by VictorBarbosaMartins — CHANGES_REQUESTED** [review]
Hi @orelgueta, thanks for adding this functionality, it looks good. Please, complement with the following:
- add to the docstring also the raise statement
- add a integration test for this functionality, ex. `python applications/get_parameter.py --parameter altitude --site North --model_version prod5`

**Comment by orelgueta** [comment]
Thanks for the review. I added those two points. I should mention though that we never had `Raises` in the applications. I added it here cause it's always good to have, but we might want to add it to all other applications as well.

**Review by VictorBarbosaMartins — APPROVED** [review]
Great, thanks. lets merge once the tests are successful

**Comment by VictorBarbosaMartins** [comment]
> Thanks for the review. I added those two points. I should mention though that we never had `Raises` in the applications. I added it here cause it's always good to have, but we might want to add it to all other applications as well.

Indeed, I just realized that now. I will do the rest in the documentation PR

**Comment by GernotMaier** [comment]
> Thanks for the review. I added those two points. I should mention though that we never had `Raises` in the applications. I added it here cause it's always good to have, but we might want to add it to all other applications as well.

I this something we want to have? My idea was always:
- modules and classes raise exceptions, as they are called by applications or other classes which can / should handle the exception (depend on the use case)
- errors in applications should trigger a logger.error or logger.critical and then an application quit. This is a level with direct communication with the users, do we expect them to understand KeyErrors or similar? I am really not sure.

**Comment by orelgueta** [comment]
I agree, but we also print out a meaningful error to the user. So essentially we are just using python's built in `raise` function instead of some `os.exit` command to exit. It seems reasonable to me. Whether it should be in the documentation I am not sure, but the code I am confident about.

**Pull request merged**
