### PR TITLE
Introduction of general CI tools

### PR DESCRIPTION
**Pull request by GernotMaier**
Introduce some general CI tools using Github Action.

The following steps are outline in the .github/workflows/CI.yml : 

1. install conda dependencies
2. run pyflakes
3. run pytests

This is done for python version 3.6, 3.7, 3.8 and are running for each *pull_request*.

Tests for 2. and 3. are failing at this point:
- pyflakes: some minor code updates are required (unless we plan to pyflakes with different options?)
- pytests need access to configuration data and data from instrument teams.

### CODE REVIEW

**Comment by RaulRPrado** [comment]
I am trying to understand how to fit this.

So, in order to make the pyflake pass, I have to fix all its messages. Is that right?

I mean, these messages:

./simtools/db_handler.py:996:50 undefined name 'newValue'
./simtools/psf_analysis.py:[40](https://github.com/gammasim/gammasim-tools/runs/5036767822?check_suite_focus=true#step:5:40)5:9 local variable 'center' is assigned to but never used
./simtools/simtel/simtel_config_writer.py:50:9 dictionary key 'trigger_telescopes' repeated with different values
./simtools/simtel/simtel_config_writer.py:52:9 dictionary key 'trigger_telescopes' repeated with different values
./simtools/simtel/simtel_runner.py:171:13 local variable 'sysOutput' is assigned to but never used
./simtools/simtel/simtel_runner_array.py:2:1 'os' imported but unused
./simtools/tests/test_simtel_events.py:60:13 local variable 'simEvents' is assigned to but never used
./simtools/tests/test_array_simulator.py:54:13 local variable 'newArraySimulator' is assigned to but never used
./simtools/util/legend_handlers.py:[41](https://github.com/gammasim/gammasim-tools/runs/5036767822?check_suite_focus=true#step:5:41):9 local variable 'width' is assigned to but never used
./simtools/util/legend_handlers.py:41:17 local variable 'height' is assigned to but never used
./simtools/util/legend_handlers.py:62:9 local variable 'width' is assigned to but never used
./simtools/util/legend_handlers.py:62:17 local variable 'height' is assigned to but never used
./simtools/util/legend_handlers.py:83:9 local variable 'width' is assigned to but never used
./simtools/util/legend_handlers.py:83:17 local variable 'height' is assigned to but never used
./applications/validate_camera_efficiency.py:120:5 redefinition of unused 'plt' from line 46
./applications/validate_camera_fov.py:124:5 redefinition of unused 'plt' from line [44](https://github.com/gammasim/gammasim-tools/runs/5036767822?check_suite_focus=true#step:5:44)
./applications/get_parameter.py:74:9 'raise NotImplemented' should be 'raise NotImplementedError'
./applications/compare_cumulative_psf.py:209:5 redefinition of unused 'plt' from line 73
Error: Process completed with exit code 1.

**Comment by GernotMaier** [comment]
Maybe wait with putting work into this and first cross check with Karl what the recommended approach is. Would be wrong to invest time now, while maybe we should use pyflakes with certain options. I will send Karl a mail now.

**Comment by RaulRPrado** [comment]
I actually fixed them already. A couple of them were actually bugs, so it is good we had a look at it.

And I added pyflakes to the env.

**Comment by GernotMaier** [comment]
Ok - very good.

Any ideas if we can run the unit tests without the database or other external dependencies?

**Comment by RaulRPrado** [comment]
We could redesign the tests for it, but we would not be testing much of the code without the DB and sim_telarray. So not sure if it is worth it.

**Comment by GernotMaier** [comment]
How many of the testing function actually need a connected to the DB, and how many just need some input configuration data? I would assume that most of the tests need only some input data.

Unit tests are more useful if they run automatically, so independence of a lot of input sources would be good. We could also put on a cloud directory a configuration sample and the tests without the DB with those configuration files?

**Comment by RaulRPrado** [comment]
Do we intend to merge this PR? If not, I should open another PR with the changes to fix the pyflakes. Some of them are important.

**Comment by GernotMaier** [comment]
If you are ok with it, then please merge. You will get CI building errors until the linter has been fixed (but we are free to ignore them).

**Comment by RaulRPrado** [comment]
> If you are ok with it, then please merge. You will get CI building errors until the linter has been fixed (but we are free to ignore them).

The pyflakes is fine now, the problem is the pytest because of DB access. Could you comment out the pytest from the CI now until we fix it?

**Comment by GernotMaier** [comment]
All checks are passing now (pyflakes, without pytests). Thanks!

**Comment by RaulRPrado** [comment]
Keeping the discussion in this closed PR:

Without DB and sim_telarray, 46/97 tests failed. So if we find a way to select the tests based on that, we will be testing half of the code. And I'd say it would be the least important half.

When we wrote the test units, we weren't particularly worried about writing tests that do not use DB or sim_telarray. So from now on, knowing that this is a thing, the tests could be designed more carefully to optimize them without DB/sim_telarray.

**Comment by GernotMaier** [comment]
1. simtel_array: this shouldn't be an issue, we could either download the tar package and compile it each time or use a docker container to run it (both is possible on github actions)
2. DB access: do we need DB access (to test mongo-DB specific routines) or do we need access to the configuration files?
    - for db access only: would it be sufficient to have a small dummy db for that, installed instantanious in the action process?
    - configuration files: could we access them locally, or pull them from somewhere without using DB access?

**Comment by GernotMaier** [comment]
For the second items, we should have a script to retrieve / update test data from the DB, to make sure that we keep synced.

Anyway, we should open up the DB for outside access.

**Pull request merged**
