### PR TITLE
Documentation of auxiliary files / data directory

### PR DESCRIPTION
**Pull request by GernotMaier**
Added one small page to describe the files in the data directory.

Note that I've moved [data/corsika/corsika_parameters.yml](https://github.com/gammasim/gammasim-tools/blob/master/data/corsika/corsika_parameters.yml) into /data/parameter/corsika_parameters.yml, as I had a hard time to write a sentence in the documentation justifying a separate directory (this is why some modules required changes).

### CODE REVIEW

**Comment by orelgueta** [comment]
I think we decided to keep some files in this directory to allow for tests which do not require a DB connection. I might remember wrongly though.

**Comment by VictorBarbosaMartins** [comment]
> I think we decided to keep some files in this directory to allow for tests which do not require a DB connection. I might remember wrongly though.

Hmm, I see. If we need those for tests I suggest using tests/resources instead, otherwise, I don't see the reason why we should keep two directories with data

**Comment by GernotMaier** [comment]
Shouldn't start the habit of discussing code changes in pull requests...

In my understanding we do:
- add to database anything which is related to the MC model 
- add to the test/resources directory anything which is needed for tests.

These data files are different:
- the data/parameters files are required to test user input for e.g., correct units. 
- data data/layout files are required to run the trigger threshold application (there is a discussion in #329 on it as well). These are model version independent.

I think this is a consistent approach and ok for now.

In future, we might consider to write the layout files dynamically; it is so simple and therefore not necessary to really keep them as files.

**Review by VictorBarbosaMartins — APPROVED** [review]
Ok!

**Pull request merged**
